### ISSUE TITLE
削除された項目の扱い

### ISSUE THREAD

**Issue by RyoheiGoto** [citbrains/RoboCupRule#7]
B 人間の参考データ
この項目は最新のルールでは無くなっているため, どう扱うかを決める必要があります.
また, 残しておくなら翻訳が不正確なためやり直す必要があります.

**Comment by yasuohayashibara** [comment]
ルール変更で削除されている部分に関しては削除しても良いと思います．

**Comment by DaikiMaekawa** [comment]
@RyoheiGoto @yasuohayashibara 徐々に更新していくのも良いと思いますが、年度ごとのフォルダを作って管理するというのはどうでしょうか?

**Comment by minakata** [comment]
前川くんに賛成です。
・現在のルールだけでは過去の事情が見えてこない
・人間のデータについてはこのリーグの最終的な目標なのでまた付録として復活する可能性が高い

**Comment by RyoheiGoto** [comment]
対処が完了したのでcloseします.
