### ISSUE TITLE
RoboCup2019ルール確認

### ISSUE THREAD

**Issue by jsupratman13** [citbrains/RoboCupRule#8]
https://www.robocuphumanoid.org/materials/rules/
特に重要な変更点や情報を確認する.

**Comment by jsupratman13** [comment]
## TDPの重要な変更点：
* TCの時に最大2機体まで動作しても良い（ロボット変更は可能だが常に合計2機体まで）
### Push Recoveryの変更点
* その場歩き
* ロープの長さは1.5mから2m
* プッシュ：前、後ろ、前か後ろ
### High Jump
* ジャンプした後3秒以上立ったままにする
### High Kick
* 障害物の最低高さボール直径2/3
* ボールがフィールドから出る、ロボットが障害物を触れる、及びボールが障害物の正面を触れたらTCの失敗となる

**Comment by jsupratman13** [comment]
## ハードウェアの変更点
* 全機体に緊急停止ボタンを追加する（アクチュエータに電源を止めるスイッチ）
   * その上に最大2個ボタン追加可能：戦略をスタート・ストップする（アクセライトスイッチと同じ）
   * 別のボタンがある場合は試合中に使われないような目印をつける（DIPスイッチにマスキングテープとか）
* ロボットの足の比率は1.2:3.5
* チームカラー

## 試合ルールに変更点
* kick-offから一発で点を決めるのはノーカウント（相手がふれるもしくはボールがセンターサークルから出た後）

**Comment by matsumotokoki** [comment]
https://www.robocuphumanoid.org/materials/rules/
最終バージョンのリンクです。

**Comment by matsumotokoki** [comment]
http://www.robocuphumanoid.org/wp-content/uploads/RCHL-2019-Rules-changesMarked.pdf
最終バージョンのリンクです。

**Comment by matsumotokoki** [comment]
フィールドに変更点がありました。
ペナルティーマーク:[2.1m] --> [1.5m]

**Comment by jsupratman13** [comment]
サブした後の機体がまたプレイすることができるよになったそうです。

**Comment by HayatoKitaura** [comment]
２０１８年までで１５章のスローインについてのルールが記載されてないのですが今回も和訳する必要はないのでしょうか。

**Comment by jsupratman13** [comment]
@HayatoKitaura 
> スローイン(throw in)の場合、ボールが出たところのタッチラインの上に置かれる。フリーキックモードに入る。

のことかな？
それとも実際のスローインのやりかたの話？

**Comment by HayatoKitaura** [comment]
@jsupratman13
説明不足ですみません。
現在1年生が2019年のルールの和訳を行っているのですが、15章のスローインについての和訳が今までされてきて無かったようなので今回もする必要はないのでしょうか？

**Comment by jsupratman13** [comment]
@HayatoKitaura 
なるほど。
優先順位が高くないけど時間があればやってください。

**Comment by jsupratman13** [comment]
多分知っていると思うが念の為
### エントリーする位置
#### キックオフの時
自分のハーフコート以内のタッチラインであればどこでも（センターラインの近く置いたり、ゴール近くてもok）
#### その他
ペナルティマーク付近

**Comment by jsupratman13** [comment]
ロボカップ2019終了したためissueをcloseします
